[req]
distinguished_name = req_distinguished_name
x509_extensions = v3_req
prompt = no

[req_distinguished_name]
CN = api.bancasegura.test
O = BancaSegura
C = CO

[v3_req]
subjectAltName = @alt_names

[alt_names]
DNS.1 = api.bancasegura.test
IP.1 = 10.0.2.2
